const items = [
  {
    id: 1,
    name: "item1",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake1.jfif"
  },
  {
    id: 2,
    name: "item2",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake2.jfif"
  },
  {
    id: 3,
    name: "item3",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake3.jfif"
  },
  {
    id: 4,
    name: "item4",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake4.jfif"
  },
  {
    id: 5,
    name: "item5",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake5.jfif"
  },
  {
    id: 6,
    name: "item6",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake6.jfif"
  },
  {
    id: 7,
    name: "item7",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake7.jfif"
  },
  {
    id: 8,
    name: "item8",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake8.jfif"
  },
  {
    id: 9,
    name: "item9",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake1.jfif"
  },
  {
    id: 10,
    name: "item10",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake2.jfif"
  },
  {
    id: 11,
    name: "item11",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake3.jfif"
  },
  {
    id: 12,
    name: "item12",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake4.jfif"
  },
  {
    id: 13,
    name: "item13",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake5.jfif"
  },
  {
    id: 14,
    name: "item14",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake6.jfif"
  },
  {
    id: 15,
    name: "item15",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "Top",
    image: "assets/Items_files/Cake7.jfif"
  },
  {
    id: 16,
    name: "item16",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Cake",
    bestSeller: "None",
    image: "assets/Items_files/Cake8.jfif"
  },
  {
    id: 17,
    name: "item17",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee1.jpg",
  },
  {
    id: 18,
    name: "item18",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee6.jfif",
  },
  {
    id: 19,
    name: "item19",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee7.jfif",
  },
  {
    id: 20,
    name: "item20",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee8.jfif",
  },
  {
    id: 21,
    name: "item21",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee5.jfif",
  },
  {
    id: 22,
    name: "item22",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee6.jfif",
  },
  {
    id: 23,
    name: "item23",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee7.jfif",
  },
  {
    id: 24,
    name: "item24",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee8.jfif",
  },
  {
    id: 25,
    name: "item25",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee1.jpg",
  },
  {
    id: 26,
    name: "item26",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee7.jfif",
  },
  {
    id: 27,
    name: "item27",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee8.jfif",
  },
  {
    id: 28,
    name: "item28",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee6.jfif",
  },
  {
    id: 29,
    name: "item29",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "Top",
    image: "assets/Items_files/Coffee5.jfif",
  },
  {
    id: 30,
    name: "item30",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee6.jfif",
  },
  {
    id: 31,
    name: "item31",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee7.jfif",
  },
  {
    id: 32,
    name: "item32",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Coffee",
    bestSeller: "None",
    image: "assets/Items_files/Coffee8.jfif",
  },
  {
    id:33,
    name: "item33",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT1.jfif"
  },
  {
    id:34,
    name: "item34",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT2.jfif"
  },
  {
    id: 35,
    name: "item35",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT3.jfif"
  },
  {
    id:36,
    name: "item36",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT4.jfif"
  },
  {
    id: 37,
    name: "item37",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT5.jfif"
  },
  {
    id: 38,
    name: "item38",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT6.jfif"
  },
  {
    id: 39,
    name: "item39",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT7.jfif"
  },
  {
    id: 40,
    name: "item40",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT8.jfif"
  },
  {
    id:41,
    name: "item41",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT1.jfif"
  },
  {
    id: 42,
    name: "item42",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT2.jfif"
  },
  {
    id: 43,
    name: "item43",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT3.jfif"
  },
  {
    id: 44,
    name: "item44",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT4.jfif"
  },
  {
    id: 45,
    name: "item45",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "Top",
    image: "assets/Items_files/MT5.jfif"
  },
  {
    id: 46,
    name: "item46",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT6.jfif"
  },
  {
    id: 47,
    name: "item47",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT7.jfif"
  },
  {
    id: 48,
    name: "item48",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Milk Tea",
    bestSeller: "None",
    image: "assets/Items_files/MT8.jfif"
  },
  {
    id: 49,
    name: "item49",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea1.jfif"
  },
  {
    id: 50,
    name: "item50",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea2.jfif"
  },
  {
    id: 51,
    name: "item51",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea3.jfif"
  },
  {
    id: 52,
    name: "item52",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea4.jfif"
  },
  {
    id: 53,
    name: "item53",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea5.jfif"  
  },
  {
    id: 54,
    name: "item54",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea6.jfif"
  },
  {
    id:55,
    name: "item55",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea7.jfif"
  },
  {
    id: 56,
    name: "item56",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea8.jfif"
  },
  {
    id:57,
    name: "item57",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea1.jfif"
  },
  {
    id: 58,
    name: "item58",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea2.jfif"
  },
  {
    id: 59,
    name: "item59",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea3.jfif" 
  },
  {
    id: 60,
    name: "item60",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea4.jfif"
  },
  {
    id: 61,
    name: "item61",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea5.jfif"
  },
  {
    id: 62,
    name: "item62",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea6.jfif"
  },
  {
    id: 63,
    name: "item63",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea7.jfif"
  },
  {
    id: "64",
    name: "item64",
    price: 100000,
    rate: 4.5,
    feature: "Feature -,-",
    category: "Tea",
    bestSeller: "None",
    image: "assets/Items_files/Tea8.jfif"
  },
];

export default items;
