const order = [
    {
        id: 1,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Delivered",
    },
    {
        id: 2,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Process",
    },
    {
        id: 3,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Delivered",
    },
    {
        id: 4,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Process",
    },
    {
        id: 5,
        branch: "branch2",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Cash on Delivery",
        status: "Delivered",
    },
    {
        id: 6,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Canceled",
    },
    {
        id: 7,
        branch: "branch3",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Cash on Delivery",
        status: "Delivered",
    },
    {
        id: 8,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Process",
    },
    {
        id: 9,
        branch: "branch2",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Cash on Delivery",
        status: "Delivered",
    },
    {
        id: 10,
        branch: "branch3",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Cash on Delivery",
        status: "Delivered",
    },
    {
        id: 11,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Canceled",
    },
    {
        id: 12,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Cash on Delivery",
        status: "Delivered",
    },
    {
        id: 13,
        branch: "branch2",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Transfer Bank",
        status: "Delivered",
    },
    {
        id: 14,
        branch: "branch1",
        customer: "abc",
        date: "12/12/2023",
        amount:"$14.5",
        payment: "Cash on Delivery",
        status: "Canceled",
    },
]

export default order;