const staff = [
    {
        id: 1,
        name: "Matt Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 2,
        name: "Matt 2323",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 3,
        name: "23 Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 4,
        name: "Matt 124",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 5,
        name: "24 Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 6,
        name: "Matt 57",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 7,
        name: "574 Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 8,
        name: "Matt 574",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 9,
        name: "Matt 574",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 10,
        name: "Matt 574",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    }, {
        id: 11,
        name: "Matt Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 12,
        name: "Matt 2323",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 13,
        name: "23 Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 14,
        name: "Matt 124",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 15,
        name: "24 Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 16,
        name: "Matt 57",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 17,
        name: "574 Dickerson",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 18,
        name: "Matt 574",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 19,
        name: "Matt 574",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    {
        id: 20,
        name: "Matt 574",
        email: "email@email.com",
        dob: "12/05/2022",
        branch: "Branch1",
    },
    // Add more rows as needed
];

export default staff;